export {default as Navbar} from './navbar'
export {default as Footer} from './footer'
export {default as About} from './about'
export {default as GameAccounts} from './gameacc'
export {default as NotFound} from './404'